<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Contracts\" />
      <Folder Include="Handlers\" />
      <Folder Include="Mappers\" />
      <Folder Include="Validators\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MeridianHost.Domain\MeridianHost.Domain.csproj" />
    </ItemGroup>

</Project>
